# Generated by Django 3.2.2 on 2021-08-28 19:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=150)),
                ('date', models.DateField(default=datetime.date(2021, 8, 29))),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('adress_text', models.CharField(max_length=120)),
                ('adress_google', models.CharField(max_length=50)),
                ('star_rate', models.FloatField(default=1)),
                ('info', models.TextField(default='')),
                ('Bar', models.BooleanField(default=False)),
                ('Fitnes_Club', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Гостиница',
                'verbose_name_plural': '1.Гостиницы',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('quantity_room', models.CharField(choices=[('1', 'Одноместный'), ('2', 'Двухместный'), ('3', 'Трёхместный'), ('4', 'Четерёхместный')], max_length=20)),
                ('type_room', models.CharField(choices=[('default', 'Обычный'), ('lux', 'Люкс')], max_length=10)),
                ('book_room', models.CharField(default='Free', max_length=5)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotels')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': '3.Номера',
            },
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(default=datetime.date(2021, 8, 29))),
                ('date_to', models.DateTimeField(default=datetime.date(2021, 8, 30))),
                ('FirstName', models.CharField(default='', max_length=40)),
                ('LastName', models.CharField(default='', max_length=40)),
                ('Passport_Serial', models.CharField(default='AA', max_length=4)),
                ('Passport_Number', models.IntegerField(default=1234567, max_length=10)),
                ('hotel_name_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.rooms')),
            ],
            options={
                'verbose_name': 'Госты',
                'verbose_name_plural': '5.ФИО Госты',
            },
        ),
        migrations.CreateModel(
            name='description_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('refrigerator', models.BooleanField(default=False)),
                ('radio', models.BooleanField(default=False)),
                ('sauna', models.BooleanField(default=False)),
                ('Extra_long_beds', models.BooleanField(default=False)),
                ('Walk_in_closet', models.BooleanField(default=False)),
                ('Baby_safety_gates', models.BooleanField(default=False)),
                ('Desk', models.BooleanField(default=False)),
                ('Clothes_rack', models.BooleanField(default=False)),
                ('Heating', models.BooleanField(default=False)),
                ('Board_games_puzzles', models.BooleanField(default=False)),
                ('Iron', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.rooms')),
            ],
            options={
                'verbose_name': 'Описание номер',
                'verbose_name_plural': '4.Описании номера',
            },
        ),
    ]
