# Generated by Django 3.2.8 on 2021-11-04 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20210830_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='date_from',
            field=models.DateTimeField(default=datetime.date(2021, 11, 4)),
        ),
        migrations.AlterField(
            model_name='guests',
            name='date_to',
            field=models.DateTimeField(default=datetime.date(2021, 11, 5)),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='date',
            field=models.DateField(default=datetime.date(2021, 11, 4)),
        ),
    ]
